services:
  - type: web
    name: homeops-backend
    env: node
    buildCommand: npm ci --only=production
    startCommand: node index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 