services:
  - type: static_site
    name: homeops-frontend
    buildCommand: echo "No build needed"
    publishDir: public
    branch: main
      - key: OPENAI_API_KEY
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REDIRECT_URI
        value: https://homeops-agent.onrender.com/auth/google/callback
    healthCheckPath: /
    autoDeploy: true 