services:
  - type: web
    name: -homeops-agent
    env: node
    buildCommand: npm install
    startCommand: node quick-server.js
    branch: email-decoder-onboarding
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REDIRECT_URI
        value: https://homeops-agent.onrender.com/auth/google/callback
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: homeops-web
    healthCheckPath: /api/test
    autoDeploy: true 