services:
  - type: web
    name: homeops-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 